name: bookingcourtapp
description: "Booking Court App"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  http: ^1.2.2
  firebase_core: ^4.15.0
  cloud_firestore: ^6.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/image/1.jpg
    - lib/image/2.jpg
    - lib/image/member1.jpg
    - lib/image/member2.jpg

  