// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Bb8sbpvz8XOUB90hTl29xIjfKajgpnI',
    appId: '1:9857082835:web:e27a9f229ec2211de4fb26',
    messagingSenderId: '9857082835',
    projectId: 'flutterproject-a0929',
    authDomain: 'flutterproject-a0929.firebaseapp.com',
    storageBucket: 'flutterproject-a0929.firebasestorage.app',
    measurementId: 'G-D981CEYZCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvFCrqGMpp0bV5C1uNpRndkSOwT7yE4Mk',
    appId: '1:9857082835:android:53ecd42de64135fae4fb26',
    messagingSenderId: '9857082835',
    projectId: 'flutterproject-a0929',
    storageBucket: 'flutterproject-a0929.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaG2vedEaAM6spXsSL5-L3FUek8RM5Ins',
    appId: '1:9857082835:ios:8e338cceea5ff58fe4fb26',
    messagingSenderId: '9857082835',
    projectId: 'flutterproject-a0929',
    storageBucket: 'flutterproject-a0929.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaG2vedEaAM6spXsSL5-L3FUek8RM5Ins',
    appId: '1:9857082835:ios:8e338cceea5ff58fe4fb26',
    messagingSenderId: '9857082835',
    projectId: 'flutterproject-a0929',
    storageBucket: 'flutterproject-a0929.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6Bb8sbpvz8XOUB90hTl29xIjfKajgpnI',
    appId: '1:9857082835:web:b239828ac673122ce4fb26',
    messagingSenderId: '9857082835',
    projectId: 'flutterproject-a0929',
    authDomain: 'flutterproject-a0929.firebaseapp.com',
    storageBucket: 'flutterproject-a0929.firebasestorage.app',
    measurementId: 'G-794MLPF3RR',
  );
}
